# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('text', redactor.fields.RedactorField(blank=True, max_length=4294967295, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
