# Generated by Django 5.2.5 on 2025-09-01 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, max_length=4294967295, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
