# Generated by Django 5.2.5 on 2025-09-01 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Company name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('website', models.URLField(verbose_name='Website')),
                ('role', models.CharField(max_length=256, verbose_name='Specific Role')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('summary', models.TextField(blank=True, max_length=40000, null=True, verbose_name='Business Summary')),
                ('team_desc', models.TextField(blank=True, max_length=40000, null=True, verbose_name='Team Description')),
                ('pre_emption_rights', models.BooleanField(default=False, verbose_name='Pre-emption Rights')),
                ('voting_rights', models.BooleanField(default=False, verbose_name='Voting Rights')),
                ('class_a', models.BooleanField(default=False, verbose_name='Share Class A')),
                ('class_b', models.BooleanField(default=False, verbose_name='Share Class B')),
                ('funding_stage', models.CharField(blank=True, choices=[('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D')], default='', max_length=30, null=True, verbose_name='Current Funding State')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('doc', models.FileField(upload_to='attach', verbose_name='File')),
                ('uploadedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
                ('uploadedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.industry'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companies', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is main image?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='companies.company')),
            ],
            options={
                'ordering': ['-is_main'],
            },
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Member, Occupation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='companies.company')),
            ],
        ),
    ]
