# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20150810_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name=b'Title')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='funding_stage',
            field=models.CharField(blank=True, choices=[(b'series_a', b'Series A'), (b'series_b', b'Series B'), (b'series_c', b'Series C'), (b'series_d', b'Series D')], default=b'', max_length=30, null=True, verbose_name=b'Current Funding State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Industry'),
        ),
    ]
