# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20160118_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='funding_stage',
            field=models.CharField(blank=True, choices=[(b'seed', b'Seed'), (b'series_a', b'Series A'), (b'series_b', b'Series B'), (b'series_c', b'Series C'), (b'series_d', b'Series D')], default=b'', max_length=30, null=True, verbose_name=b'Current Funding State'),
        ),
    ]
