"""
Django settings for credio project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django_jinja.builtins import DEFAULT_EXTENSIONS

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEBSITE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
PROJECT_ROOT = os.path.abspath(os.path.dirname(WEBSITE_ROOT))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w0&++iu9-n-bh0ddu2*wuq7*u$$qt0bp$i)t%4x5%v5lf)h4l='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['liquidround.dev.4-com.pro', 'localhost']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipeline',
    'django_forms_bootstrap',

    'accounts',
    'statpages',
    'companies',
    'listings',
    'admindeck',
    'msgs',
    'news',
    'redactor',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'django_jinja.middleware.JinjaMiddleware',
)

AUTHENTICATION_BACKENDS = (
    # ... your other backends
    'accounts.auth_backend.TokenBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(WEBSITE_ROOT, 'templates/admindeck'),
            os.path.join(WEBSITE_ROOT, 'templates/listings'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
           ],
        },
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            os.path.join(WEBSITE_ROOT, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'core.jinja.environment',
            'extensions': DEFAULT_EXTENSIONS + ['pipeline.jinja2.PipelineExtension'],
            # 'context_processors': [
            #     'django.template.context_processors.debug',
            #     'django.template.context_processors.request',
            #     'django.contrib.auth.context_processors.auth',
            #     'django.contrib.messages.context_processors.messages',
            # ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'liquidround',
        'USER': 'root',
        'PASSWORD': '1111',
        'HOST': 'localhost',
        'PORT': 5432
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_DIRS = (
    ('js', os.path.join(WEBSITE_ROOT, 'core/static/js')),
    # ('css', os.path.join(WEBSITE_ROOT, 'core/static/less')),
    ('css', os.path.join(WEBSITE_ROOT, 'core/static/css')),
    ('images', os.path.join(WEBSITE_ROOT, 'core/static/images')),
    ('img', os.path.join(WEBSITE_ROOT, 'core/static/img')),
    #('fonts', os.path.join(WEBSITE_ROOT, 'core/static/fonts')),
    #('font', os.path.join(WEBSITE_ROOT, 'core/static/font')),
    #('img', os.path.join(WEBSITE_ROOT, 'core/static/img')),

    # ('img', os.path.join(PROJECT_ROOT, 'img')),
    # ('vendor', os.path.join(PROJECT_ROOT, 'bower_components')),
)



STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    'pipeline.finders.CachedFileFinder',
    'pipeline.finders.PipelineFinder',
)

STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'

PIPELINE_CSS_COMPRESSOR = None
PIPELINE_JS_COMPRESSOR = None

PIPELINE_COMPILERS = (
    'pipeline.compilers.less.LessCompiler',
)

PIPELINE = {
    'PIPELINE_ENABLED': False,
    'STYLESHEETS': {
        'styles': {
            'source_filenames': (
                'css/plugins/bootstrap/css/bootstrap.min.css',
                'css/style.css',
                'css/header-default.css',
                'css/footer-v3.css',
                'css/plugins/animate.css',
                'css/plugins/line-icons/line-icons.css',
                'css/plugins/font-awesome/css/font-awesome.min.css',
                'css/plugins/image-hover/css/img-hover.css',
                'css/theme-colors/default.css',
                'css/theme-skins/dark.css',
                #'css/font-awesome.css',
                #'css/chosen.min.css',
                # 'css/blocks.css',
                'css/main.css',
            ),
            'output_filename': 'css/styles.css',
            # 'variant': 'datauri',
        },
    },
    'JAVASCRIPT': {
        'scripts_bottom': {
            'source_filenames': (
                'js/jquery/jquery.min.js',
                'js/jquery/jquery-migrate.min.js',
                'js/bootstrap/js/bootstrap.min.js',
                'js/back-to-top.js',
                'js/smoothScroll.js',
                'js/jquery.parallax.js',
                'js/image-hover/js/touch.js',
                'js/image-hover/js/modernizr.js',
                'js/jquery.mockjax.js',
                'js/jquery.autocomplete.min.js',
                'js/jquery.jscroll.min.js',
                'js/hogan.min.js',
                'js/templates.js',
                'js/app.js',
                'js/main.js',

            ),
            'output_filename': 'js/scripts_bottom.js',
        }
    }
}
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static/')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'

REDACTOR_OPTIONS = {'lang': 'en'}
REDACTOR_UPLOAD = 'uploads/'