# Generated by Django 5.2.5 on 2025-09-01 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=4000)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('new', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='listings.listing')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_from', to='accounts.profile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_to', to='accounts.profile')),
            ],
        ),
    ]
