# Generated by Django 5.2.5 on 2025-09-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=4294967295, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('top_menu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.PositiveIntegerField()),
                ('titlle', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
