# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 08:35
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=redactor.fields.RedactorField(blank=True, max_length=4294967295, null=True),
        ),
    ]
