# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statpages', '0002_auto_20160126_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('position', models.PositiveIntegerField()),
            ],
        ),
    ]
