# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statpages', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=b'Description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='titlle',
            field=models.CharField(default='title', max_length=128, verbose_name=b'Title'),
            preserve_default=False,
        ),
    ]
