# Generated by Django 5.2.5 on 2025-09-01 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('certified', models.CharField(choices=[('hnwi', 'I certify that I am a High Net Worth Investor'), ('si', 'I certify that I am a qualified Sophisticated Investor')], default='hnwi', max_length=10, verbose_name='Certified')),
                ('activationcode', models.CharField(blank=True, max_length=255, null=True)),
                ('activatedon', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
