# Generated by Django 5.2.5 on 2025-09-01 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(choices=[('equity', 'Equity'), ('offer', 'Offer')], default='equity', max_length=15)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('approvedon', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('closedon', models.DateTimeField(blank=True, null=True)),
                ('expireson', models.DateTimeField(blank=True, null=True)),
                ('prolong_code', models.CharField(blank=True, max_length=256, null=True)),
                ('prolong_messaged', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.profile')),
            ],
        ),
    ]
